// This file was generated by liblab | https://liblab.com/

package io.github.mlanlazc.services;

import static org.junit.Assert.assertTrue;

import org.junit.jupiter.api.*;

public class BaseServiceTest {
  //@BaseServiceTest
  //@DisplayName("BaseServiceTest that base service is working")
  //public void test() {}
  // TODO: Add base service test code here
}
