// This file was generated by liblab | https://liblab.com/

package io.github.mlanlazc.examples;

import io.github.mlanlazc.Petstoremilan;
import io.github.mlanlazc.exceptions.ApiException;

public class Main {

  public static void main(String[] args) {
    Petstoremilan client = new Petstoremilan();
    try {
      Object response = client.petsService.listPets(7);
      System.out.println(response);
    } catch (ApiException e) {
      e.printStackTrace();
    }
  }
}
