// This file was generated by liblab | https://liblab.com/

package io.m.hooks;

import io.m.hooks.model.Hook;
import io.m.hooks.model.Request;
import io.m.hooks.model.Response;

public class CustomHook implements Hook {

  @Override
  public void beforeRequest(Request request) {
    // no-op
  }

  @Override
  public void afterResponse(Request request, Response response) {
    // no-op
  }

  @Override
  public void onError(Request request, Exception exception) {
    // no-op
  }
}
